#!/bin/bash

cd $SNAP_USER_COMMON

if [ ! -d "$SNAP_USER_COMMON/logs" ]; then
    mkdir -p "$SNAP_USER_COMMON/logs"
fi


#snapcraft-preload mycroft-messagebus >> /$SNAP_USER_COMMON/logs/bus.log 2>&1 &
#snapcraft-preload mycroft-enclosure-client >> /$SNAP_USER_COMMON/logs/enclosure.log 2>&1 &
snapcraft-preload mycroft-audio >> /$SNAP_USER_COMMON/logs/audio.log 2>&1 &
#snapcraft-preload mycroft-speech-client >> /$SNAP_USER_COMMON/logs/voice.log 2>&1 &
snapcraft-preload mycroft-skills >> /$SNAP_USER_COMMON/logs/skills.log 2>&1 &


mycroft-cli-client

echo "Stopping all processes..."
killall mycroft-skills
killall mycroft-enclosure-client
killall mycroft-speech-client
killall mycroft-audio
echo "Stopped"
