#!/bin/sh 
# Credit: https://gist.github.com/darth-veitcher/f47eb0a52ae42a1c5e9a65adca460723

PIDFILE=/tmp/useraudio.pid

if [ -f $PIDFILE ]
then
  PID=$(cat $PIDFILE)
  ps -p $PID > /dev/null 2>&1
  if [ $? -eq 0 ]
  then
    echo "Process already running"
    exit 1
  else
    ## Process not found assume not running
    echo $$ > $PIDFILE
    if [ $? -ne 0 ]
    then
      echo "Could not create PID file"
      exit 1
    fi
  fi
else
  echo $$ > $PIDFILE
  if [ $? -ne 0 ]
  then
    echo "Could not create PID file"
    exit 1
  fi
fi

TMPDIR=/tmp/audio
export TMPDIR
mkdir -p $TMPDIR

cd $SNAP_USER_COMMON

$SNAP/bin/mycroft-audio

rm $PIDFILE