
#adopt-info: mycroft
name: mycroft
version: 'dev'
base: core18
confinement: strict
summary: Your AI personal assistant!
description: |
  Mycroft is a free and open-source intelligent personal assistant and
  knowledge navigator for Linux-based operating systems that uses a natural language user
  interface. It is the world''s first fully open-source AI voice assistant.

  Mycroft is named after a fictional computer from 1966 science fiction novel 
  "The Moon Is a Harsh Mistress".

  Installing skills by voice seems to be broken for now, but you can use
  the `mycroft.msm` command to list, install, and remove skills.

environment:
  LOCPATH: $SNAP/usr/lib/locale
  MYCROFT_WEB_CACHE: $SNAP_USER_DATA/mycroft_web_cache.json

plugs:
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes:sounds-themes
    interface: content
    target: $SNAP/data-dir/sounds

grade: stable
layout:
  /etc/mycroft/mycroft.conf:
    bind-file: $SNAP/etc/mycroft/mycroft.conf
  /var/tmp:
    bind: $SNAP_COMMON/vartmp
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /opt/mycroft/skills:
    bind: $SNAP/skills
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa


apps:
  messagebus:
    command-chain: 
      - bin/snapcraft-preload
    command: $SNAP/bin/mycroft-messagebus
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind
  
  
  skills:
    command-chain: [bin/snapcraft-preload] 
    command: bin/start_skills
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind

    
  audio:
    command: $SNAP/bin/snapcraft-preload $SNAP/bin/mycroft-audio
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
      PULSE_RUNTIME_PATH: /var/run/pulse
      PULSE_SYSTEM: 1
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind

  speech:
    command-chain: [bin/snapcraft-preload,snap/command-chain/alsa-launch]
    command: $SNAP/bin/mycroft-speech-client
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind
  

  enclosure:
#    command-chain: 
#      - bin/snapcraft-preload
    command: $SNAP/bin/mycroft-enclosure-client
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind


  mycroft:
    command-chain: 
      - snap/command-chain/alsa-launch
      - bin/copy-autostart
      #- bin/snapcraft-preload
    command: bin/mycroft-launch
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    desktop: usr/share/applications/mycroft.desktop
    autostart: mycroft.desktop
    extensions:
    - gnome-3-28
    plugs:
    - alsa
    - audio-playback
    - audio-record
    - pulseaudio
    - desktop
    - desktop-legacy
    - mount-observe
    - network
    - network-bind
    - x11

parts:
  snapcraft-preload:
    build-packages:
    - try:
      - gcc-multilib
      - g++-multilib
    plugin: cmake
    source: https://github.com/forslund/snapcraft-preload.git
    source-branch: no-as-needed
    stage-packages:
    - try:
      - lib32stdc++6

  mycroft:
    after: [snapcraft-preload]
    #source: https://github.com/mycroftai/mycroft-core.git
    source: ./mycroft-core
    #source-branch: 'bugfix/issue-2727'
    plugin: python
    python-version: python3
    build-packages: 
      - python3-wheel
      - gcc
      - swig
      - g++
      - libfann2
      - libfann-dev
    stage-packages: [python3-pyaudio, python3-six, libfann2, git, python3-pip, python-alsaaudio, mpg123, vlc]
#    python-packages: [six==1.13.0, pocketsphinx==0.1.0, fann2==1.0.7, padatious==0.4.8]
    python-packages: 
      - pyalsaaudio
      - ddg3
      - fann2==1.0.7
      - feedparser
      - geocoder
      - holidays
      - ifaddr
      - mtranslate
      - multi_key_dict
      - num2words
      - pyjokes
      - pyowm
      - pytz
      - timezonefinder
      - wikipedia
      - wolframalpha
      - py_mplayer
      - pychromecast
      - python-vlc
    


  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    stage-packages: [libasound2-plugins]
    build-packages:
      - libasound2-dev

  static:
    plugin: dump
    source: static


  mimic:
    after: [snapcraft-preload, mycroft]
    build-packages: [libpcre2-dev, portaudio19-dev]
    configflags:
    - --prefix=/usr
    - --disable-static
    plugin: autotools
    prime:
    - usr/bin
    - usr/include
    - usr/lib
    - -usr/lib/*.a
    - -usr/lib/*.la
    - -usr/lib/pkgconfig
    - usr/share/mimic
    source: https://github.com/MycroftAI/mimic.git
    source-depth: 1
    source-type: git
    stage-packages:
    - libpcre2-8-0
  
  precise:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl -LOJ $(curl https://raw.githubusercontent.com/MycroftAI/precise-data/dist/x86_64/latest)
      curl -OJ https://raw.githubusercontent.com/MycroftAI/precise-data/models/hey-mycroft.tar.gz
    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise precise-engine_*.tar.gz
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise hey-mycroft.tar.gz
  

  mycroft-installer:
    source: https://github.com/MycroftAI/skill-installer.git
    plugin: dump
    organize:
      '*': lib/python3.6/site-packages/mycroft-installer/

  skils:
    plugin: dump
    source: ./skills
    override-pull: |
      mkdir skills
      cd skills
      for url in https://github.com/MycroftAI/skill-query \
        https://github.com/mycroftai/fallback-unknown \
        https://github.com/mycroftai/fallback-wolfram-alpha \
        https://github.com/mycroftai/skill-alarm \
        https://github.com/mycroftai/skill-audio-record \
        https://github.com/mycroftai/skill-configuration \
        https://github.com/mycroftai/skill-date-time \
        https://github.com/mycroftai/fallback-duckduckgo \
        https://github.com/mycroftai/skill-hello-world \
        https://github.com/mycroftai/skill-installer \
        https://github.com/mycroftai/skill-ip \
        https://github.com/mycroftai/skill-joke \
        https://github.com/mycroftai/skill-naptime \
        https://github.com/mycroftai/skill-npr-news \
        https://github.com/mycroftai/skill-pairing \
        https://github.com/mycroftai/skill-personal \
        https://github.com/mycroftai/skill-playback-control \
        https://github.com/mycroftai/skill-reminder \
        https://github.com/mycroftai/skill-singing \
        https://github.com/mycroftai/skill-speak \
        https://github.com/mycroftai/skill-spelling \
        https://github.com/mycroftai/skill-stock \
        https://github.com/mycroftai/skill-stop \
        https://github.com/mycroftai/skill-support \
        https://github.com/mycroftai/mycroft-timer \
        https://github.com/mycroftai/skill-version-checker \
        https://github.com/mycroftai/skill-volume \
        https://github.com/mycroftai/skill-weather \
        https://github.com/mycroftai/skill-wiki;
        do git clone $url
      done