
#adopt-info: mycroft
name: mycroft
version: 'dev'
base: core18
confinement: strict
summary: Your AI personal assistant!
description: |
  Mycroft is a free and open-source intelligent personal assistant and
  knowledge navigator for Linux-based operating systems that uses a natural language user
  interface. It is the world''s first fully open-source AI voice assistant.

  Mycroft is named after a fictional computer from 1966 science fiction novel 
  "The Moon Is a Harsh Mistress".

  Installing skills by voice seems to be broken for now, but you can use
  the `mycroft.msm` command to list, install, and remove skills.

environment:
  LOCPATH: $SNAP/usr/lib/locale

plugs:
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes:sounds-themes
    interface: content
    target: $SNAP/data-dir/sounds

grade: stable
layout:
  /etc/mycroft/mycroft.conf:
    bind-file: $SNAP/etc/mycroft/mycroft.conf
  /usr/include:
    bind: $SNAP/usr/include
  /var/tmp:
    bind: $SNAP_COMMON/vartmp
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /opt/mycroft/skills:
    bind: $SNAP_COMMON/mycroft-data/skills
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa


apps:
  messagebus:
    command: $SNAP/bin/snapcraft-preload $SNAP/bin/mycroft-messagebus
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind
  
  
  skills:
    command-chain: [bin/snapcraft-preload] 
    command: bin/start_skills
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind

    
  audio:
    command: $SNAP/bin/snapcraft-preload $SNAP/bin/mycroft-audio
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
      PULSE_RUNTIME_PATH: /var/run/pulse
      PULSE_SYSTEM: 1
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind

  speech:
    command: $SNAP/bin/snapcraft-preload $SNAP/bin/mycroft-speech-client
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind
  

  enclosure:
    command: $SNAP/bin/snapcraft-preload $SNAP/bin/mycroft-enclosure-client
    daemon: simple
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    extensions:
    - gnome-3-28
    plugs:
    - mount-observe
    - network
    - network-bind


  mycroft:
    command-chain: 
      - snap/command-chain/alsa-launch
      - bin/copy-autostart
      - bin/snapcraft-preload
    command: bin/mycroft-launch
    environment:
      SWIG_LIB: $SNAP/usr/share/swig3.0
      GIT_EXEC_PATH: $SNAP/usr/lib/git-core/
      MPG123_MODDIR: $SNAP/usr/lib/x86_64-linux-gnu/mpg123
    desktop: usr/share/applications/mycroft.desktop
    autostart: mycroft.desktop
    extensions:
    - gnome-3-28
    plugs:
    - alsa
    - audio-playback
    - audio-record
    - pulseaudio
    - desktop
    - desktop-legacy
    - mount-observe
    - network
    - network-bind
    - x11

parts:
  snapcraft-preload:
    build-packages:
    - try:
      - gcc-multilib
      - g++-multilib
    plugin: cmake
    source: https://github.com/forslund/snapcraft-preload.git
    source-branch: no-as-needed
    stage-packages:
    - try:
      - lib32stdc++6

  mycroft:
    after: [snapcraft-preload]
    source: https://github.com/mycroftai/mycroft-core.git
    plugin: python
    python-version: python3
    build-packages: 
      - python3-wheel
      - gcc
      - swig
      - g++
      - libfann2
      - libfann-dev
    stage-packages: [python3-pyaudio, python3-six, libfann2, git, python3-pip]
#    python-packages: [six==1.13.0, pocketsphinx==0.1.0, fann2==1.0.7, padatious==0.4.8]
    python-packages: [fann2==1.0.7]
    override-build: |
      echo "LS0tIGxvY2sucHkub3JpZwkyMDIwLTEwLTEwIDEyOjAwOjQ4Ljc0Njc4Mzc1NCAtMDcwMAorKysgbG9jay5weS5uZXcJMjAyMC0xMC0xMCAxMjowMToyMS4yNzQ0NTk4OTggLTA3MDAKQEAgLTk4LDggKzk4LDggQEAKIAogICAgICMKICAgICAjIENsYXNzIGNvbnN0YW50cwotICAgIERJUkVDVE9SWSA9ICcvdG1wL215Y3JvZnQnCi0gICAgRklMRSA9ICcve30ucGlkJworICAgIERJUkVDVE9SWSA9ICcvdG1wJworICAgIEZJTEUgPSAnL215Y3JvZnQue30ucGlkJwogCiAgICAgIwogICAgICMgQ29uc3RydWN0b3IK" |
      base64 -d | patch mycroft/lock/__init__.py
      snapcraftctl build


  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev

  static:
    plugin: dump
    source: static


  mimic:
    after: [snapcraft-preload, mycroft]
    build-packages: [libpcre2-dev, portaudio19-dev]
    configflags:
    - --prefix=/usr
    - --disable-static
    plugin: autotools
    prime:
    - usr/bin
    - usr/include
    - usr/lib
    - -usr/lib/*.a
    - -usr/lib/*.la
    - -usr/lib/pkgconfig
    - usr/share/mimic
    source: https://github.com/MycroftAI/mimic.git
    source-depth: 1
    source-type: git
    stage-packages:
    - libpcre2-8-0
  
  precise:
    plugin: nil
    build-packages:
      - curl
    override-pull: |
      curl -LOJ $(curl https://raw.githubusercontent.com/MycroftAI/precise-data/dist/x86_64/latest)
      curl -OJ https://raw.githubusercontent.com/MycroftAI/precise-data/models/hey-mycroft.tar.gz
    override-build: |
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise precise-engine_*.tar.gz
      install -m644 -D -t $SNAPCRAFT_PART_INSTALL/precise hey-mycroft.tar.gz
  

  mycroft-installer:
    source: https://github.com/MycroftAI/skill-installer.git
    plugin: dump
    organize:
      '*': lib/python3.6/site-packages/mycroft-installer/

