#!/bin/sh

set -e

if [ ! -d "$SNAP_COMMON/vartmp" ]; then
    mkdir -m1777 "$SNAP_COMMON/vartmp"
else
    chmod 1777 "$SNAP_COMMON/vartmp"
fi

snapctl stop --disable mycroft.skills
snapctl stop --disable mycroft.audio