#!/bin/sh

set -e

if [ ! -d "$SNAP_COMMON/vartmp" ]; then
    mkdir -m1777 "$SNAP_COMMON/vartmp"
else
    chmod 1777 "$SNAP_COMMON/vartmp"
fi

# if this is not Ubuntu Core, then disable the audio service
if ! grep -q snap_core= /proc/cmdline
then 
    snapctl stop --disable mycroft.audio
fi